### ISSUE TITLE
sync of sameforall emums sends setAttributeInAllVariants update action when it is not needed

### ISSUE THREAD

**Issue by briantomkins** [commercetools/commercetools-project-sync#361]
During syncing product drafts, which completely match with corresponding products in CT, sync library always adds an update action (setAttributeInAllVariants for 'Same for all' and setAttribute for 'None' attribute constraints) for attributes of ENUM type. After syncing, the 'Date modified' attribute for product is not updated.

Steps to reproduce:
1) Create product type with single attribute of type 'enum'
2) Create product with new product type
3) Sync product draft with the same data (key, slug, attributes, ...) as new product

Expected:
Sync completed: Summary: 1 products were processed in total (0 created, 0 updated and 0 failed to sync)

Actual:
Sync completed: Summary: 1 products were processed in total (0 created, 1 updated and 0 failed to sync).

SUPPORT-14962

**Comment by butenkor** [comment]
Currently both project-sync and sync-java library do not support changing the product type of the product since there is no update action from the API which would allow that. In order to change the product type the existing product would have to be completely deleted from the project and recreated from scratch. Since some data like prices and other product attributes might be set by a different import process (other than product-sync/product-import) the library never deletes products but rather creates or updates them only. Please delete the products for which the product type has changed in the target project manually and after that run the project-sync again.

I hope it helps - please let us know if you have any issues with the suggested approach.

**Comment by ahmetoz** [comment]
Issue is resolved on the support channels.
