### ISSUE TITLE
Sync does not process all the products

### ISSUE THREAD

**Issue by pavvell** [commercetools/commercetools-project-sync#399]
hi! I noticed that after the sync completes, in the summary section it says that it processed less number of products that we have in the source project. in our case it processes only 4598, while we have more than 7000 products. 

I'm using such command: 
```
commercetools/commercetools-project-sync:5.2.0 -s products
```

I understand that without the `-f` flag it only does a delta sync, but it still works the same way even after removing the custom object of the run or if a new run name was provided. 

running the command with -f flag seems does nothing at all:
```
commercetools/commercetools-project-sync:5.2.0 -f products
```

it just stops execution after a few seconds without any output at all.

do you guys know what could be the reason of this behaviour? or any suggestion on how to debug it?

**Comment by lojzatran** [comment]
Hi @pavvell,

Thanks for reaching out to us.

I checked the code to see if there are any problems but I could not find one. Since you are currently the only one having the issue with syncing, it is most probably related to your project.

As you [can see here](https://github.com/commercetools/commercetools-project-sync/blob/d47e81f336fbb2704c2deb7d60da763e731ba788/src/main/java/com/commercetools/project/sync/Syncer.java#L125), when running delta sync we first fetch the custom object timestamp and then using this timestamp we [create a query to fetch the products](https://github.com/commercetools/commercetools-project-sync/blob/d47e81f336fbb2704c2deb7d60da763e731ba788/src/main/java/com/commercetools/project/sync/Syncer.java#L192). The custom object should be in the format [`container: 'commercetools-project-sync.{runnerName}.{syncModuleName}' and key: {sourceProjectKey}`](https://github.com/commercetools/commercetools-project-sync/blob/d47e81f336fbb2704c2deb7d60da763e731ba788/src/main/java/com/commercetools/project/sync/service/impl/CustomObjectServiceImpl.java#L69).

---

I also checked why the full sync doesn't work. It seems like you have to provide the sync module option first. It should be in this format:
```
commercetools/commercetools-project-sync:5.2.0 -s products -f
```
Please try again in this format and let us know if it is working. I will also create a ticket to address the issue that there was no output at all when options were provided in a different order.

----

If you still cannot sync correctly, we might need to dig deeper into your project. In this case, please create a [commercetools support ticket](https://jira.commercetools.com/servicedesk/customer/portal/1) so that we can get access to your project.
