### ISSUE TITLE
product sync and lack of logs

### ISSUE THREAD

**Issue by valtechtmn** [commercetools/commercetools-project-sync#477]
Hi guys,

first of all thanks for a fantastic tool that has tremendously helped me and my team to setup new projects with initial data.
I have two small comments or questions :

1) Product references
In our products we have some field referencing other products (e.g field type Reference (product)). And that is well handled by the sync in the most part, except in cases where there are circular references, I've seen two examples where the sync tool is unable to manage

- two (or more) products referencing each other
- a product referencing itself (yeah I know it's a dumb case but just saying!)

More-over although the tool is giving the number or products which are missing references there is no log telling us which products those are so we may manually fix the issue.

2) Unknown issue
I stumbled on an issue that I can't figure out, here are the logs from the import :
`{"timestamp":"2023-08-17T10:11:42.102475Z","severity":"ERROR","loggerName":"com.commercetools.project.sync.product.ProductSyncer","message":"Error when trying to sync product. Existing key: <<not present>>. Update actions: []","stackHash":"95cda0f3","stackTrace":"j.l.IllegalArgumentException: argument \"content\" is null\n\tat c.f.j.d.ObjectReader._assertNotNull(ObjectReader.java:2456)\n\tat c.f.j.d.ObjectReader.readValue(ObjectReader.java:1720)\n\tat i.s.s.j.SphereJsonUtils.lambda$readObject$9(SphereJsonUtils.java:240)\n\tat i.s.s.j.SphereJsonUtils.executing(SphereJsonUtils.java:326)\n\tat i.s.s.j.SphereJsonUtils.readObject(SphereJsonUtils.java:240)\n\tat c.c.s.c.h.GraphQlBaseRequestImpl.deserializeWithResourceName(GraphQlBaseRequestImpl.java:77)\n\tat c.c.s.c.h.ResourceKeyIdGraphQlRequest.deserialize(ResourceKeyIdGraphQlRequest.java:46)\n\tat c.c.s.c.h.ResourceKeyIdGraphQlRequest.deserialize(ResourceKeyIdGraphQlRequest.java:23)\n\tat i.s.s.c.SphereClientImpl.parse(SphereClientImpl.java:139)\n\tat i.s.s.c.SphereClientImpl.processHttpResponse(SphereClientImpl.java:129)\n\tat i.s.s.c.SphereClientImpl.lambda$executeWithRecover$4(SphereClientImpl.java:86)\n\tat j.u.c.CompletableFuture$UniApply.tryFire(Unknown Source)\n\t... 6 common frames omitted\nWrapped by: j.u.c.CompletionException: java.lang.IllegalArgumentException: argument \"content\" is null\n\tat j.u.c.CompletableFuture.encodeThrowable(Unknown Source)\n\tat j.u.c.CompletableFuture.completeThrowable(Unknown Source)\n\tat j.u.c.CompletableFuture$BiRelay.tryFire(Unknown Source)\n\tat j.u.c.CompletableFuture$CoCompletion.tryFire(Unknown Source)\n\t... 11 common frames omitted\nWrapped by: c.c.s.c.e.SyncException: Failed to build a cache of keys to ids.\n\tat c.c.s.c.BaseSync.handleError(BaseSync.java:153)\n\tat c.c.s.p.ProductSync.lambda$processBatch$0(ProductSync.java:183)\n\tat j.u.c.CompletableFuture$UniCompose.tryFire(Unknown Source)\n\tat j.u.c.CompletableFuture.postComplete(Unknown Source)\n\tat j.u.c.CompletableFuture.completeExceptionally(Unknown Source)\n\tat i.s.s.u.CompletableFutureUtils.lambda$transferResult$0(CompletableFutureUtils.java:86)\n\tat j.u.c.CompletableFuture.uniWhenComplete(Unknown Source)\n\tat j.u.c.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)\n\tat j.u.c.CompletableFuture$Completion.exec(Unknown Source)\n\tat j.u.c.ForkJoinTask.doExec(...\n"}`

Unfortunately the problematic product id is not logged so it's hard to find it out. I was able to find the incriminated product on the source project but nothing looks off to me.

Lastly : can we make an option like "keep going in case of error" ? That would be really helpful to get all the working products out of the way when only a couple are failing.

Thanks a lot

**Comment by salander85** [comment]
Hey @valtechtmn,

thank you for your great feedback. We are happy to support you with this tool. 
We can give you the following answers:

1. Product references:
Unfortunately the tool cannot handle circular references or product's referencing themselves, because the nature of resolving references is to keep track of missing products and importing as soon as these are available. So, in case of a product referencing itself it will keep waiting to be imported til it is imported... 

As said, the tool keeps track of missing products. This is done via customObject in the CTP project. So, if you have this case you can query for customObjects with container named `commercetools-sync-java.UnresolvedReferencesService.productDrafts` . It will return customObjects with value containing the productDraft and a list of keys which are the missing product references.

```javascript
      "value": {
        "productDraft": {
          "key": "product-With-Missing-References",
          // includes other product data
        },
        "missingReferencedProductKeys": [
          "product-1",
          "product-2"
        ]
      }
``` 
3. Unknownn issue:
This looks like an issue with the GraphQl endpoint of the CTP platform. The tool fetches the referenced product id's but the platform responds with a null-result which is causing this issue. A quick solution could be deleting the product-references of this incriminated product you found.

As the error-message is pretty useless here, i will create an internal ticket to adjust it.

Lastly: At the moment we are migrating the product-sync to a new version, which makes the current one deprecated. As this request is pretty complex we will not provide it for the current version. 

Hope we could answer your questions.

Regards

**Comment by valtechtmn** [comment]
Hey @salander85,

Thanks for taking the time to answer all my questions.
The custom object trick will definitely come in handy next time !

As for the unknown bug, I'm not sure I understood your explanation. You are saying when the tool fetch the existing product on the source project he gets a null value ? For the entire product or just some specific field ? Or some other entity (variant / price / channel / referenced product) ?
I've looked carefully for a potentially empty reference but can't see any, maybe it's not showing in the UI and I need to grab a JSON representation of the product through REST API to catch it. If you have any more information about which field or entity could be a likely suspect from the error thrown I could try to have a second look. Otherwise I'm happy enough with your response and will close this issue.

Regards

**Comment by salander85** [comment]
Hi @valtechtmn ,

you are welcome. 

Here are more details on the unknown bug issue:
In a first step, the tool transforms the data of the source project to `draft` which is required from the platform to create data. In this step the tool resolves references on the given resource. 
The unknown bug issue happens when the tool fetches referenced product of variant attribute fields of the product. 
Please try to delete all referenced products and try again. 
Please gimme an update afterwards. Might be an issue with the platform.

Regards

**Comment by salander85** [comment]
Hi @valtechtmn ,

we recently released a new version of this tool [commercetools-project-sync 5.4.2](https://github.com/commercetools/commercetools-project-sync/releases/tag/5.4.2). Please make sure to use this version. 

As we haven't got any feedback on this topic from your side, we will close this issue.
